### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by myangelkamikaze** [ElectronicObserverEN/EOTools#2]
Right now, if a config doesn't exist, tools will crash because of a file not found exception. It would probably be better to generate an empty file if the config doesn't exist yet.

![image](https://user-images.githubusercontent.com/40002167/218919583-13bce00b-89b7-46df-af49-1f1d46e556b2.png)

**Comment by Jebzou** [comment]
Fixed, did some cleanup and added a config page
