### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by myangelkamikaze** [ElectronicObserverEN/EOTools#3]
It looks like the database needs to be migrated manually before using? Consider running database migrations on startup (in MainWindow constructor, probably).
```cs
using EOToolsDbContext context = new();
context.Database.Migrate();
```

![image](https://user-images.githubusercontent.com/40002167/218920560-9c98b1cb-428c-4887-8ffc-ef8d323e1fc9.png)

**Comment by Jebzou** [comment]
Added migration on startup
